api/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import serializers, viewsets, routers



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
from api.views import EmployeeListView, LocationListView, ExcelDocumentView, EmployeeCreateApiView, \
    EmployeeRetrieveAPIView, EmployeeUpdateAPIView, EmployeeDestroyAPIView,LocationCreateApiView, LocationUpdateAPIView,LocationDestroyAPIView, LocationRetrieveAPIView

app_name = 'api'
urlpatterns = [
	url(r'^employees/$', EmployeeListView.as_view(), name='employees-list'),
	url(r'^employees/create/$', EmployeeCreateApiView.as_view(), name='employees-create'),
	url(r'^employees/view/(?P<pk>[0-9]+)/$', EmployeeRetrieveAPIView.as_view(), name='employees-view'),
	url(r'^employees/edit/(?P<pk>[0-9]+)/$', EmployeeUpdateAPIView.as_view(), name='employees-edit'),
	url(r'^employees/remove/(?P<pk>[0-9]+)/$', EmployeeDestroyAPIView.as_view(), name='employees-remove'),


	url(r'^customers/$', LocationListView.as_view(), name='customers'),
	url(r'^customers/create/$', LocationCreateApiView.as_view(), name='customers-create'),
	url(r'^customers/view/(?P<pk>[0-9]+)/$', LocationRetrieveAPIView.as_view(), name='customers-view'),
	url(r'^customers/edit/(?P<pk>[0-9]+)/$', LocationUpdateAPIView.as_view(), name='customers-edit'),
	url(r'^customers/remove/(?P<pk>[0-9]+)/$', LocationDestroyAPIView.as_view(), name='customers-remove'),


	url(r'^excel-documents/$', ExcelDocumentView.as_view(), name='excel-document'),
]

timeopt/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils import translation
from django.views import generic
from django.views.static import serve
from content.views import *
from django.views import static
from django.conf import settings
from general import set_lang as core_views


urlpatterns = [
    url('grappelli/', include('grappelli.urls')), # grappelli URLS
    # url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    # url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^administration/', admin.site.urls,name="admin"),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media'),

    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^api/', include("api.urls", namespace="api")),

]
translation.activate(settings.LANGUAGE_CODE)

urlpatterns += i18n_patterns(
    url(r'^test/$', index, name="index"),
    url(r'^set-language/$',core_views.set_language,  name='set_language'),
    url(r'^', include("timeopt.core.urls", namespace="core")),
    # url(r'^', include("general.urls", namespace="general")),
    # url(r'^', include("tour.urls", namespace="tour")),
    url(r'^', include("userprofile.urls", namespace="userprofile")),
    # url(r'^account/', include("base_user.urls", namespace="account")),
)

urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
    ]
urlpatterns += staticfiles_urlpatterns()

userprofile/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from .views import *


urlpatterns = [


	url(r'^log-out/$', log_out, name='log-out'),
	url(r'^sign-in/$', sign_in, name='sign_in'),
	url(r'^d/change-password/$', change_password, name='change-password'),
	url(r'^$', dashboard, name='dashboard'),
	url(r'^d/plan-prepare/$', plan_prepare, name='plan-prepare'),
	url(r'^d/all-customer-dates/view/$', all_customer_dates, name='all-customer-dates'),
	url(r'^d/all-customer-dates/generated/$', all_customer_dates_generated, name='all-customer-dates-generated'),
	url(r'^d/plan-prepare/ajax/(?P<op_slug>[\w-]+)/$', plan_prepare_ajax, name='plan-prepare-ajax'),
	url(r'^d/employee-show-plan/ajax/$', employee_plan_show_ajax, name='employee-plan-ajax'),
	url(r'^d/change-employee-plan-day/ajax/(?P<first_id>[0-9]+)/$', change_plan_employee_day, name='change-employee-plan-day-ajax'),
	url(r'^d/move-employee-plan-day/ajax/(?P<from_id>[0-9]+)/$', move_employee_plan_day, name='move-employee-plan-day-ajax'),
	url(r'^d/admin-customer-from-excel/$', customer_upload_from_excel, name='admin-customer-upload-from-excel'),
	url(r'^d/admin-employee-show-plan/ajax/(?P<e_id>[0-9]+)/$', admin_employee_plan_show_ajax, name='admin-employee-plan-ajax'),
	url(r'^d/admin-employee-generate-plan-pdf/ajax/(?P<e_id>[0-9]+)/$', pdf_plan_generate_ajax, name='admin-pdf-plan-generate-ajax'),
	url(r'^d/admin-employee-weekly-generate-plan-pdf/ajax/(?P<pew_id>[0-9]+)/(?P<week_item>[0-9]+)/$', pdf_plan_weekly_generate_ajax, name='admin-pdf-plan-weekly-generate-ajax'),
	url(r'^d/admin-employee-plan-form-generate/ajax/$', admin_employee_plan_form_generate_ajax, name='admin-employee-plan-form-generate-ajax'),
	url(r'^d/admin-employee-plan-form-customer-ajax/ajax/(?P<e_p_id>[0-9]+)/(?P<l_id>[0-9]+)/$', admin_employee_plan_form_location_ajax, name='admin-employee-plan-form-location-ajax'),
	url(r'^d/admin-employee-plan-form-change-location-position-ajax/ajax/(?P<cur_loc_ord_id>[0-9]+)/$', admin_employee_plan_form_change_location_position_ajax, name='admin-change-customer-position-ajax'),
	url(r'^d/admin-employee-plan-daily-optimization/ajax/(?P<pew_id>[0-9]+)/$', daily_optimization_ajax, name='admin-employee-plan-daily-optimization'),
	url(r'^d/admin-employee-plan-location-lock/ajax/(?P<loc_id>[0-9]+)/$', lock_unlock_ajax, name='admin-location-lock-unlock-ajax'),
	url(r'^d/admin-employee-show-map-plan/ajax/(?P<pew_id>[0-9]+)/$', admin_employee_plan_show_map_ajax, name='admin-employee-plan-map-ajax'),
	url(r'^d/admin-all-employees-plans/$', admin_all_employees_plans, name='admin-all-employees-plans'),
	url(r'^d/admin-all-customers/$', admin_all_customers, name='admin-all-customers'),
	url(r'^d/admin-all-employees-plans/employee/(?P<e_id>[0-9]+)/$', admin_employee_plans, name='admin-employee-plans'),
	url(r'^d/all-plans/$', all_plans, name='all-plans'),
	url(r'^d/my-plans/$', my_plans, name='my-plans'),
	# url(r'^forgot-password/$', forgot_password, name='forgot_password'),

    # url(r'^contact/$', 'home.views.contact',name='contact'),

]

userprofile/views.py
import copy
import json

from django.conf import settings
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, get_user_model

from django.contrib.auth.views import logout
# Create your views here.
from django.urls import reverse
from django.utils import timezone
from django.utils.datetime_safe import datetime

from content.new_main import exc_list_loc
from userprofile.forms import *
from django.utils.translation import ugettext as _

from userprofile.models import Profile
from content.models import *

from content.tasks import   add_location_from_excel_list,main_result_prepare_plan_new_plan, sub_main_result_prepare_plan_new_plan
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from flynsarmy_paginator.paginator import FlynsarmyPaginator
from django.template.loader import render_to_string
GUser = get_user_model()

def base(req=None):
    company_information = CompanyInformation.objects.filter(active=True).order_by('-date').first()
    settings_obj = Settings.objects.filter().order_by('-date').first()
    data = {
        'now':datetime.now(),
        'base_company_information':company_information,
        'base_settings_obj':settings_obj,
    }
    return data

def base_auth(req=None):
    user = req.user
    profile = get_object_or_404(Profile, user=user)
    company_information = CompanyInformation.objects.filter(active=True).order_by('-date').first()
    settings_obj = Settings.objects.filter().order_by('-date').first()
    data = {
        'now':datetime.now(),
        'base_profile':profile,
        'base_plan_log':PlanLog.objects.filter(complated=False,rejcected=False),
        'base_company_information':company_information,
        'base_settings_obj':settings_obj,
    }
    return data



@login_required(login_url='userprofile:sign_in')
def dashboard(request):
    from datetime import timedelta
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    # tourpackeges = None
    now = timezone.now()
    context = base_auth(req=request)
    employees = Employee.objects.all()
    customers = Location.objects.filter(our_company=False)
    # create_location_user_locations.delay()
    if profile.type == 'admin-person':
        pass
    elif profile.type == 'employee-person':
        pass
    else:
        raise Http404
    # return HttpResponse(customers[:20].count())
    context['datetime1'] = timedelta(hours=8) + timedelta(minutes=46)
    context['employee_count'] = employees.count()
    context['customer_count'] = customers.count()
    context['last_customers'] = customers.all()[:20]
    context['last_employees'] = employees.all()[:20]
    # context['tours'] = Tour.objects.filter(active=True)
    return render(request, 'userprofile/dashboard.html', context=context)




@login_required(login_url='userprofile:sign_in')
def customer_upload_from_excel(request):
    context = base_auth(req=request)
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    context['message_code'] = 0
    if profile.type == 'admin-person':
        pass
    else:
        raise Http404
    if request.method == 'POST':
        form = ExcelDocumentForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            clean_data = form.cleaned_data
            excelfile = clean_data.get('excelfile')
            extension = os.path.splitext(excelfile.name)[1]
            if not (extension in IMPORT_FILE_TYPES):
                context['message_code'] = 2
                context['message'] = _("Please choose Excel File")
                return render(request, 'userprofile/admin/add-customer-excel.html', context=context)
                # raise forms.ValidationError(
                #     _("This file is not a valid Excel file. Please make sure your input file is an Excel file )"))
            # pass
            excel_document_new = ExcelDocument(excelfile=excelfile)
            excel_document_new.save()
            # return HttpResponse(excelfile)
            context['message_code'] = 1
            # print("excel_document_new.excelfile.url={}".format(excel_document_new.excelfile.url))
            # print("excel_document_new.excelfile={}".format(excel_document_new.excelfile))
            add_location_from_excel_list.delay(excel_document_new.excelfile.url)
            context['message'] = _("Uploaded successfuly")

        else:
            context['message_code'] = 2
            context['message'] = _("Please choose Excel File")
            # return HttpResponse(form.errors)
            # newdoc = ExcelDocumentForm(excelfile = request.FILES['excelfile'])
            # newdoc.save()

            # return HttpResponseRedirect(reverse('credit.views.list'))
    else:
        form = ExcelDocumentForm()
    context['form'] = form
    return render(request, 'userprofile/admin/add-customer-excel.html', context=context)





@login_required(login_url='userprofile:sign_in')
def all_plans(request):
    context = base_auth(req=request)
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    if profile.type == 'admin-person':
        pass
    else:
        raise Http404
    return render(request, 'userprofile/admin/all_plans.html', context=context)

@login_required(login_url='userprofile:sign_in')
def my_plans(request):
    context = base_auth(req=request)
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    context['employee'] = get_object_or_404(Employee,profile=profile)
    context['week_list'] = [1,2,3]

    if profile.type == 'employee-person':
        pass
    else:
        raise Http404
    return render(request, 'userprofile/employee/plans.html', context=context)


@login_required(login_url='userprofile:sign_in')
def plan_prepare(request):
    context = base_auth(req=request)
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    if profile.type == 'admin-person':
        pass
    else:
        raise Http404
    return render(request, 'userprofile/admin/plan_prepare.html', context=context)


@login_required(login_url='userprofile:sign_in')
def all_customer_dates(request):
    context = base_auth(req=request)
    from content.models import LocationDistance,Location, CompanyInformation, Employee,PlanEmployeeWork,LocationOrder,WorkDay,PlanLog
    from content.new_main import result1p1_seven as nm_result1p1_seven,result1p1_eight as nm_result1p1_eight, remove_all_exc, day_parse, general_day_parse

    user = request.user
    profile = get_object_or_404(Profile, user=user)
    if profile.type == 'admin-person':
        if request.method == 'POST' and request.is_ajax():
            message_code = 0
            message = ""
            customers = Location.objects.filter(status=True).order_by('id')
            week_2_employee_work_list = []
            week_4_employee_work_list = []
            for customers_item in customers:
                if customers_item.work_times == 2:
                    week_2_employee_work_list.append(customers_item.id)
                if customers_item.work_times == 4:
                    week_4_employee_work_list.append(customers_item.id)
            week_list = [1,2,3,4]
            day_list = [1,2,3,4,5]
            employees = Employee.objects.filter()
            week_list_i = 0
            print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^******************************************")
            daily_exc_list = [x.id for x in Location.objects.exclude(work_days=None)]
            non_daily_exc_list = [y.id for y in Location.objects.filter(work_days=None)]
            day_parse_data = day_parse(daily_exc_list)
            non_day_parse_data = general_day_parse(non_daily_exc_list)
            print("day_parse_data = day_parse([]) = {}".format(day_parse_data))
            print("non_day_parse_data = non_day_parse_data([]) = {}".format(non_day_parse_data))
            print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^******************************************")
            _html = ''
            print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^******************************************")
            print("******************************************^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
            print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^******************************************")
            all_data = {}
            all_data_exc_list = {}
            for week_list_item in week_list:
                week_list_i += 1
                weekly_exc_list = exc_list_loc(copy.deepcopy(week_2_employee_work_list), 2,
                                               week_list_item) + exc_list_loc(copy.deepcopy(week_4_employee_work_list),
                                                                              4, week_list_item)
                exc_list = weekly_exc_list
                week_day_parse_data = remove_all_exc(day_parse_data, exc_list)
                week_none_day_parse_data = remove_all_exc(non_day_parse_data, exc_list)
                # all_data['{}'.format(week_list_item)] = []
                for day_list_item in day_list:
                    daily_inc_list = week_day_parse_data['{}'.format(day_list_item)] + week_none_day_parse_data[
                        '{}'.format(day_list_item)]
                    print(">>>>>>>>>>>>>>>>>>  daily_inc_list={}  <<<<<<<<<<<<<<<<<<<<<".format(daily_inc_list))
                    print(">>>>>>>>>>>>>>>>>>  day_list_item={}  <<<<<<<<<<<<<<<<<<<<<".format(day_list_item))
                    # all_data['w-{}'.format(week_list_item)]['d-{}'.format(day_list_item)] = daily_inc_list

templates/userprofile/include/_direction_map.html
{% load static %}


    <style>
      #map {
{#        height: 100%;#}
        float: left;
        width: 100%;
        height: 500px;
      }
      #total {
        padding: 7px;
        margin: 0 0px 10px 0px;
        border-bottom: 2px dashed #26c281;
        border-top: 2px dashed #26c281;
        text-align: center;
        font-weight: 700;
        color: #333;
        font-size: 18px;
        background: azure;
      }
    </style>
    <div id="total"></div>
    <div id="map"></div>

    <script>
function initMap() {
    var $general_start_point = "";
    var $general_end_point = "";
    {% for map_data_item in map_data %}{% if forloop.first %} $general_start_point = "{{ map_data_item }}"; {% endif %}{% if forloop.last %}$general_end_point = "{{ map_data_item }}";{% endif %}{% endfor %}

  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 4,
{#    center: {lat: -24.345, lng: 134.46}  // Australia.#}
  });

  var directionsService = new google.maps.DirectionsService;
  var directionsDisplay = new google.maps.DirectionsRenderer({
    draggable: true,
    map: map,
    panel: document.getElementById('right-panel')
  });

  directionsDisplay.addListener('directions_changed', function() {
    computeTotalDistance(directionsDisplay.getDirections());
  });

  displayRoute($general_start_point, $general_end_point, directionsService,
      directionsDisplay);
}

function displayRoute(origin, destination, service, display) {
    var $general_waypoints = [
                        {% for map_data_item in map_data %}
                            {% if forloop.first or forloop.last %}{% else %}{location: "{{ map_data_item }}"},{% endif %}
                        {% endfor %}
    ];
  service.route({
    origin: origin,
    destination: destination,
    waypoints: $general_waypoints,
    travelMode: 'DRIVING',
    avoidTolls: true
  }, function(response, status) {
    if (status === 'OK') {
      display.setDirections(response);
    } else {
      alert('Could not display directions due to: ' + status);
    }
  });
}

function computeTotalDistance(result) {
  var total = 0;
  var myroute = result.routes[0];
  for (var i = 0; i < myroute.legs.length; i++) {
    total += myroute.legs[i].distance.value;
  }
  total = total / 1000;
  document.getElementById('total').innerHTML = total + ' km';
}
    </script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBDvv-kFV2Ql4HFcTVOUbyoU0qXjO_GFvs&callback=initMap"></script>

templates/userprofile/include/_employee_plans-all-customer.html
{% load static %}
{% load i18n %}
    <li class="" style="{% if in_plan %}{% else %}background:#fff3f3{% endif %}">
        <h3 class="todo-blue">{{ daily_inc__item.name }}</h3>
        <p>{{ daily_inc__item.address }}</p>
        <div class="todo-project-item-foot">
            <p class="todo-red todo-inline">{{ daily_inc__item.minute }} {% trans 'Minutes' %}</p>
        </div>
    </li>
    <div class="todo-projects-divider"></div>

templates/userprofile/include/_employee_plans.html
{% load static %}
{% load i18n %}


{#{% for employee_get_plans_w_d_get_location in employee_get_plans_w_d.get_locations %}#}
    <li class="todo-projects-item {{ employee_get_plans_w_d }} {% if forloop.counter == 1 %}todo-active{% endif %}">
        <h3 class="todo-blue">{{ employee_get_plans_w_d_get_location.location.name }}</h3>
        <p>{{ employee_get_plans_w_d_get_location.location.address }}</p>
        <div class="todo-project-item-foot">
            <p class="todo-red todo-inline">{{ work_hour }} - {{ end_work_hour }} | {{ employee_get_plans_w_d_get_location.location.minute }} {% trans 'Minutes' %}</p>
            {% if profile_type and profile_type == 'admin-person'  %}
                <p class="">
                    <button id="plan-log-edit-button-{{ employee_get_plans_w_d_get_location.id }}" {% if employee_get_plans_w_d_get_location.is_lock  %} disabled="disabled" {% endif %} onclick="showOtherPlans('{% url 'userprofile:admin-employee-plan-form-generate-ajax' %}',{{ employee_get_plans_w_d.id }},{{ employee_get_plans_w_d_get_location.location.id }},'{% url 'userprofile:admin-employee-plan-form-location-ajax' employee_get_plans_w_d.id employee_get_plans_w_d_get_location.location_id %}','{% url 'userprofile:admin-change-customer-position-ajax' employee_get_plans_w_d_get_location.id  %}')" type="button" class="btn btn-circle yellow btn-outline  btn-block" data-toggle="modal" data-target="#edit-location-order-modal">
                        <i class="fa fa-edit"></i>
                        {% trans 'Edit' %}
                    </button>
                </p>
                <p class="">
                    <button id="plan-log-lock-button-{{ employee_get_plans_w_d_get_location.id }}"
                        onclick="lockUnlock('{% url 'userprofile:admin-location-lock-unlock-ajax' employee_get_plans_w_d_get_location.id %}',{{ employee_get_plans_w_d_get_location.id }})"
                            type="button" class="btn btn-circle green btn-outline  btn-block">
                        <i class="fa fa-lock"></i>
                        {% if employee_get_plans_w_d_get_location.is_lock  %}
                            {% trans 'Unlock' %}
                        {% else %}
                            {% trans 'Lock' %}
                        {% endif %}
                    </button>
                </p>
            {% endif %}

        </div>
    </li>
    <div class="todo-projects-divider"></div>
{#{% endfor %}#}









templates/userprofile/include/_employee_plans_button.html
{% load i18n %}

{% if employee_get_plans_w_d %}
    <li class="todo-projects-item">
        <a id="show-map-button" data-ajax-url="" onclick="getDailyOptimization('{% url 'userprofile:admin-employee-plan-daily-optimization' employee_get_plans_w_d.id %}')" class="col-md-12  btn btn-md btn-circle green easy-pie-chart-reload">{% trans 'Optimizate' %}</a>
        <h3 class="todo-blue"></h3>
    </li>
{% endif %}
    <li class="todo-projects-item">
        <a id="show-map-button" data-ajax-url="" onclick="showPlanMap('{% url 'userprofile:admin-employee-plan-map-ajax' employee_get_plans_w_d.id  %}',{{ employee_get_plans_w_d_location_list }})" class="col-md-12  btn btn-md btn-circle red easy-pie-chart-reload">{% trans 'Look' %}</a>
        <h3 class="todo-blue"></h3>
    </li>
<div class="todo-projects-divider"></div>

templates/userprofile/include/_employee_plans_pdf.html
{% load static %}{% load i18n %}
<tr>
    <td colspan="2">
        <h3 class="todo-blue">{{ employee_get_plans_w_d_get_location.location.name }}</h3>
        <p>{{ employee_get_plans_w_d_get_location.location.address }}</p>
        <p class="todo-red todo-inline">{{ work_hour }} - {{ end_work_hour }} | {{ employee_get_plans_w_d_get_location.location.minute }} {% trans 'Minutes' %}</p>
        {% if employee_get_plans_w_d_get_location.location.note %}
            <p>{{ employee_get_plans_w_d_get_location.location.note }}</p>
        {% endif %}
    </td>
</tr>

templates/userprofile/include/_plan_prepare.html
{% load i18n %}
{% load static %}
<a onclick="preparePlan('main-plan-prepare-button')" {% if base_plan_log or base_settings_obj.main_plan is False %} disabled="disabled" {% endif %} id="main-plan-prepare-button" data-ajax-url="{% url 'userprofile:plan-prepare-ajax' 'main' %}"
   class="col-md-12  btn btn-md btn-circle red easy-pie-chart-reload">
    <i class="fa fa-repeat"></i> {% trans 'Prepare Plan' %}
</a>
<hr class="col-md-12"/>

<a onclick="preparePlan('sub-main-plan-prepare-button')" {% if base_plan_log or base_settings_obj.sub_plan is False %} disabled="disabled" {% endif %} id="sub-main-plan-prepare-button" data-ajax-url="{% url 'userprofile:plan-prepare-ajax' 'sub-main' %}"
   class="col-md-12  btn btn-md btn-circle yellow easy-pie-chart-reload">
    <i class="fa fa-repeat"></i> {% trans 'Prepare Sub Plan' %}
</a>

templates/userprofile/include/_week_part-all-customer.html
{% load i18n %}
    <div class="col-md-3">
        <ul class="todo-projects-container">
            <li class="todo-padding-b-0">
                <div class="todo-head">
{#                    <button class="btn btn-square btn-sm green todo-bold">{% trans 'Show Map' %}</button>#}
                    <h3>{% trans 'Week' %}: {{ week_item }}  |  {% trans 'Day' %}: {{ day_list_item }} | </h3>

                </div>
            </li>

templates/userprofile/include/_week_part.html
{% load i18n %}
    <div class="col-md-3">
        {% if employee_work_day_i == 1  %}
            <button id="admin-pdf-plan-weekly-generate-button-{{ employee_get_plans_w_d.id }}" class="btn btn-success" style="width: 100%;margin-bottom: 15px;" onclick="generateWeeklyPlanPdf('{% url 'userprofile:admin-pdf-plan-weekly-generate-ajax' employee_get_plans_w_d.id week_item %}',{{ employee_get_plans_w_d.id }})"><i class="fa fa-print"></i> {% trans 'Print' %}: {{ week_item }} {% trans 'week' %}</button>
        {% endif %}
        <ul class="todo-projects-container">
            <li class="todo-padding-b-0">
                <div class="todo-head">
{#                    <button class="btn btn-square btn-sm green todo-bold">{% trans 'Show Map' %}</button>#}
                    <h3>{% trans 'Week' %}: {{ week_item }}  |  {% trans 'Day' %}: {{ employee_work_day.day.get_day_name }} | </h3>
    {#                                                <p>4 Waiting Attention</p>#}
{#                pds{{ pdspdspds }}#}
                {% if employee_get_plans_w_d %}
{#                <p class="">#}
                <div class="mt-action-buttons " style="text-align: center;">
                    <div class="btn-group btn-group-circle">
                        <a target="_blank" onclick="onActionWeek('{% url 'userprofile:change-employee-plan-day-ajax' employee_get_plans_w_d.id %}',{{ employee_get_plans_w_d.id }},'{% trans 'Change' %}','{% trans 'Week' %}: {{ week_item }}  |  {% trans 'Day' %}: {{ employee_work_day.day.get_day_name }}')" href="javascript:void(0);" class="btn btn-outline yellow-crusta btn-sm"data-toggle="modal" data-target="#action-operation-modal">
                            {% trans 'Change' %}
                        </a>
                        <a target="_blank"  onclick="onActionWeek('{% url 'userprofile:move-employee-plan-day-ajax' employee_get_plans_w_d.id %}',{{ employee_get_plans_w_d.id }},'{% trans 'Move' %}','{% trans 'Week' %}: {{ week_item }}  |  {% trans 'Day' %}: {{ employee_work_day.day.get_day_name }}')" href="javascript:void(0);" class="btn btn-outline green btn-sm"  data-toggle="modal" data-target="#action-operation-modal">
                            {% trans 'Move' %}
                        </a>
                    </div>
                </div>
{#                </p>#}
{#                    {% else %}#}
{#                    lskalskalskal#}
                    {% endif %}
                </div>
            </li>