api/urls.py
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import serializers, viewsets, routers



# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
from api.views import EmployeeListView, LocationListView, ExcelDocumentView, EmployeeCreateApiView, \
    EmployeeRetrieveAPIView, EmployeeUpdateAPIView, EmployeeDestroyAPIView,LocationCreateApiView, LocationUpdateAPIView,LocationDestroyAPIView, LocationRetrieveAPIView

app_name = 'api'
urlpatterns = [
	url(r'^employees/$', EmployeeListView.as_view(), name='employees-list'),
	url(r'^employees/create/$', EmployeeCreateApiView.as_view(), name='employees-create'),
	url(r'^employees/view/(?P<pk>[0-9]+)/$', EmployeeRetrieveAPIView.as_view(), name='employees-view'),
	url(r'^employees/edit/(?P<pk>[0-9]+)/$', EmployeeUpdateAPIView.as_view(), name='employees-edit'),
	url(r'^employees/remove/(?P<pk>[0-9]+)/$', EmployeeDestroyAPIView.as_view(), name='employees-remove'),


	url(r'^customers/$', LocationListView.as_view(), name='customers'),
	url(r'^customers/create/$', LocationCreateApiView.as_view(), name='customers-create'),
	url(r'^customers/view/(?P<pk>[0-9]+)/$', LocationRetrieveAPIView.as_view(), name='customers-view'),
	url(r'^customers/edit/(?P<pk>[0-9]+)/$', LocationUpdateAPIView.as_view(), name='customers-edit'),
	url(r'^customers/remove/(?P<pk>[0-9]+)/$', LocationDestroyAPIView.as_view(), name='customers-remove'),


	url(r'^excel-documents/$', ExcelDocumentView.as_view(), name='excel-document'),
]

timeopt/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils import translation
from django.views import generic
from django.views.static import serve
from content.views import *
from django.views import static
from django.conf import settings
from general import set_lang as core_views


urlpatterns = [
    url('grappelli/', include('grappelli.urls')), # grappelli URLS
    # url(r'^jet/', include('jet.urls', 'jet')),  # Django JET URLS
    # url(r'^jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    url(r'^administration/', admin.site.urls,name="admin"),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media'),

    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^api/', include("api.urls", namespace="api")),

]
translation.activate(settings.LANGUAGE_CODE)

urlpatterns += i18n_patterns(
    url(r'^test/$', index, name="index"),
    url(r'^set-language/$',core_views.set_language,  name='set_language'),
    url(r'^', include("timeopt.core.urls", namespace="core")),
    # url(r'^', include("general.urls", namespace="general")),
    # url(r'^', include("tour.urls", namespace="tour")),
    url(r'^', include("userprofile.urls", namespace="userprofile")),
    # url(r'^account/', include("base_user.urls", namespace="account")),
)

urlpatterns += staticfiles_urlpatterns()




@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    return serve(request, path, document_root, show_indexes)


if settings.DEBUG is False:   #if DEBUG is True it will be served automatically
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', static.serve, {'document_root': settings.STATIC_ROOT }, name='static'),
        url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT }, name='media')
    ]
urlpatterns += staticfiles_urlpatterns()

userprofile/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns

from .views import *


urlpatterns = [


	url(r'^log-out/$', log_out, name='log-out'),
	url(r'^sign-in/$', sign_in, name='sign_in'),
	url(r'^d/change-password/$', change_password, name='change-password'),
	url(r'^$', dashboard, name='dashboard'),
	url(r'^d/plan-prepare/$', plan_prepare, name='plan-prepare'),
	url(r'^d/all-customer-dates/view/$', all_customer_dates, name='all-customer-dates'),
	url(r'^d/all-customer-dates/generated/$', all_customer_dates_generated, name='all-customer-dates-generated'),
	url(r'^d/plan-prepare/ajax/(?P<op_slug>[\w-]+)/$', plan_prepare_ajax, name='plan-prepare-ajax'),
	url(r'^d/employee-show-plan/ajax/$', employee_plan_show_ajax, name='employee-plan-ajax'),
	url(r'^d/change-employee-plan-day/ajax/(?P<first_id>[0-9]+)/$', change_plan_employee_day, name='change-employee-plan-day-ajax'),
	url(r'^d/move-employee-plan-day/ajax/(?P<from_id>[0-9]+)/$', move_employee_plan_day, name='move-employee-plan-day-ajax'),
	url(r'^d/admin-customer-from-excel/$', customer_upload_from_excel, name='admin-customer-upload-from-excel'),
	url(r'^d/admin-employee-show-plan/ajax/(?P<e_id>[0-9]+)/$', admin_employee_plan_show_ajax, name='admin-employee-plan-ajax'),
	url(r'^d/admin-employee-generate-plan-pdf/ajax/(?P<e_id>[0-9]+)/$', pdf_plan_generate_ajax, name='admin-pdf-plan-generate-ajax'),
	url(r'^d/admin-employee-weekly-generate-plan-pdf/ajax/(?P<pew_id>[0-9]+)/(?P<week_item>[0-9]+)/$', pdf_plan_weekly_generate_ajax, name='admin-pdf-plan-weekly-generate-ajax'),
	url(r'^d/admin-employee-plan-form-generate/ajax/$', admin_employee_plan_form_generate_ajax, name='admin-employee-plan-form-generate-ajax'),
	url(r'^d/admin-employee-plan-form-customer-ajax/ajax/(?P<e_p_id>[0-9]+)/(?P<l_id>[0-9]+)/$', admin_employee_plan_form_location_ajax, name='admin-employee-plan-form-location-ajax'),
	url(r'^d/admin-employee-plan-form-change-location-position-ajax/ajax/(?P<cur_loc_ord_id>[0-9]+)/$', admin_employee_plan_form_change_location_position_ajax, name='admin-change-customer-position-ajax'),
	url(r'^d/admin-employee-plan-daily-optimization/ajax/(?P<pew_id>[0-9]+)/$', daily_optimization_ajax, name='admin-employee-plan-daily-optimization'),
	url(r'^d/admin-employee-plan-location-lock/ajax/(?P<loc_id>[0-9]+)/$', lock_unlock_ajax, name='admin-location-lock-unlock-ajax'),
	url(r'^d/admin-employee-show-map-plan/ajax/(?P<pew_id>[0-9]+)/$', admin_employee_plan_show_map_ajax, name='admin-employee-plan-map-ajax'),
	url(r'^d/admin-all-employees-plans/$', admin_all_employees_plans, name='admin-all-employees-plans'),
	url(r'^d/admin-all-customers/$', admin_all_customers, name='admin-all-customers'),
	url(r'^d/admin-all-employees-plans/employee/(?P<e_id>[0-9]+)/$', admin_employee_plans, name='admin-employee-plans'),
	url(r'^d/all-plans/$', all_plans, name='all-plans'),
	url(r'^d/my-plans/$', my_plans, name='my-plans'),
	# url(r'^forgot-password/$', forgot_password, name='forgot_password'),

    # url(r'^contact/$', 'home.views.contact',name='contact'),

]

userprofile/views.py
import copy
import json

from django.conf import settings
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404, HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, get_user_model

from django.contrib.auth.views import logout
# Create your views here.
from django.urls import reverse
from django.utils import timezone
from django.utils.datetime_safe import datetime

from content.new_main import exc_list_loc
from userprofile.forms import *
from django.utils.translation import ugettext as _

from userprofile.models import Profile
from content.models import *

from content.tasks import   add_location_from_excel_list,main_result_prepare_plan_new_plan, sub_main_result_prepare_plan_new_plan
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from flynsarmy_paginator.paginator import FlynsarmyPaginator
from django.template.loader import render_to_string
GUser = get_user_model()

def base(req=None):
    company_information = CompanyInformation.objects.filter(active=True).order_by('-date').first()
    settings_obj = Settings.objects.filter().order_by('-date').first()
    data = {
        'now':datetime.now(),
        'base_company_information':company_information,
        'base_settings_obj':settings_obj,
    }
    return data

def base_auth(req=None):
    user = req.user
    profile = get_object_or_404(Profile, user=user)
    company_information = CompanyInformation.objects.filter(active=True).order_by('-date').first()
    settings_obj = Settings.objects.filter().order_by('-date').first()
    data = {
        'now':datetime.now(),
        'base_profile':profile,
        'base_plan_log':PlanLog.objects.filter(complated=False,rejcected=False),
        'base_company_information':company_information,
        'base_settings_obj':settings_obj,
    }
    return data



@login_required(login_url='userprofile:sign_in')
def dashboard(request):
    from datetime import timedelta
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    # tourpackeges = None
    now = timezone.now()
    context = base_auth(req=request)
    employees = Employee.objects.all()
    customers = Location.objects.filter(our_company=False)
    # create_location_user_locations.delay()
    if profile.type == 'admin-person':
        pass
    elif profile.type == 'employee-person':
        pass
    else:
        raise Http404
    # return HttpResponse(customers[:20].count())
    context['datetime1'] = timedelta(hours=8) + timedelta(minutes=46)
    context['employee_count'] = employees.count()
    context['customer_count'] = customers.count()
    context['last_customers'] = customers.all()[:20]
    context['last_employees'] = employees.all()[:20]
    # context['tours'] = Tour.objects.filter(active=True)
    return render(request, 'userprofile/dashboard.html', context=context)




@login_required(login_url='userprofile:sign_in')
def customer_upload_from_excel(request):
    context = base_auth(req=request)
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    context['message_code'] = 0
    if profile.type == 'admin-person':
        pass
    else:
        raise Http404
    if request.method == 'POST':
        form = ExcelDocumentForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            clean_data = form.cleaned_data
            excelfile = clean_data.get('excelfile')
            extension = os.path.splitext(excelfile.name)[1]
            if not (extension in IMPORT_FILE_TYPES):
                context['message_code'] = 2
                context['message'] = _("Please choose Excel File")
                return render(request, 'userprofile/admin/add-customer-excel.html', context=context)
                # raise forms.ValidationError(
                #     _("This file is not a valid Excel file. Please make sure your input file is an Excel file )"))
            # pass
            excel_document_new = ExcelDocument(excelfile=excelfile)
            excel_document_new.save()
            # return HttpResponse(excelfile)
            context['message_code'] = 1
            # print("excel_document_new.excelfile.url={}".format(excel_document_new.excelfile.url))
            # print("excel_document_new.excelfile={}".format(excel_document_new.excelfile))
            add_location_from_excel_list.delay(excel_document_new.excelfile.url)
            context['message'] = _("Uploaded successfuly")

        else:
            context['message_code'] = 2
            context['message'] = _("Please choose Excel File")
            # return HttpResponse(form.errors)
            # newdoc = ExcelDocumentForm(excelfile = request.FILES['excelfile'])
            # newdoc.save()

            # return HttpResponseRedirect(reverse('credit.views.list'))
    else:
        form = ExcelDocumentForm()
    context['form'] = form
    return render(request, 'userprofile/admin/add-customer-excel.html', context=context)





@login_required(login_url='userprofile:sign_in')
def all_plans(request):
    context = base_auth(req=request)
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    if profile.type == 'admin-person':
        pass
    else:
        raise Http404
    return render(request, 'userprofile/admin/all_plans.html', context=context)

@login_required(login_url='userprofile:sign_in')
def my_plans(request):
    context = base_auth(req=request)
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    context['employee'] = get_object_or_404(Employee,profile=profile)
    context['week_list'] = [1,2,3]

    if profile.type == 'employee-person':
        pass
    else:
        raise Http404
    return render(request, 'userprofile/employee/plans.html', context=context)


@login_required(login_url='userprofile:sign_in')
def plan_prepare(request):
    context = base_auth(req=request)
    user = request.user
    profile = get_object_or_404(Profile, user=user)
    if profile.type == 'admin-person':
        pass
    else:
        raise Http404
    return render(request, 'userprofile/admin/plan_prepare.html', context=context)


@login_required(login_url='userprofile:sign_in')
def all_customer_dates(request):
    context = base_auth(req=request)
    from content.models import LocationDistance,Location, CompanyInformation, Employee,PlanEmployeeWork,LocationOrder,WorkDay,PlanLog
    from content.new_main import result1p1_seven as nm_result1p1_seven,result1p1_eight as nm_result1p1_eight, remove_all_exc, day_parse, general_day_parse

    user = request.user
    profile = get_object_or_404(Profile, user=user)
    if profile.type == 'admin-person':
        if request.method == 'POST' and request.is_ajax():
            message_code = 0
            message = ""
            customers = Location.objects.filter(status=True).order_by('id')
            week_2_employee_work_list = []
            week_4_employee_work_list = []
            for customers_item in customers:
                if customers_item.work_times == 2:
                    week_2_employee_work_list.append(customers_item.id)
                if customers_item.work_times == 4:
                    week_4_employee_work_list.append(customers_item.id)
            week_list = [1,2,3,4]
            day_list = [1,2,3,4,5]
            employees = Employee.objects.filter()
            week_list_i = 0
            print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^******************************************")
            daily_exc_list = [x.id for x in Location.objects.exclude(work_days=None)]
            non_daily_exc_list = [y.id for y in Location.objects.filter(work_days=None)]
            day_parse_data = day_parse(daily_exc_list)
            non_day_parse_data = general_day_parse(non_daily_exc_list)
            print("day_parse_data = day_parse([]) = {}".format(day_parse_data))
            print("non_day_parse_data = non_day_parse_data([]) = {}".format(non_day_parse_data))
            print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^******************************************")
            _html = ''
            print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^******************************************")
            print("******************************************^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
            print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^******************************************")
            all_data = {}
            all_data_exc_list = {}
            for week_list_item in week_list:
                week_list_i += 1
                weekly_exc_list = exc_list_loc(copy.deepcopy(week_2_employee_work_list), 2,
                                               week_list_item) + exc_list_loc(copy.deepcopy(week_4_employee_work_list),
                                                                              4, week_list_item)
                exc_list = weekly_exc_list
                week_day_parse_data = remove_all_exc(day_parse_data, exc_list)
                week_none_day_parse_data = remove_all_exc(non_day_parse_data, exc_list)
                # all_data['{}'.format(week_list_item)] = []
                for day_list_item in day_list:
                    daily_inc_list = week_day_parse_data['{}'.format(day_list_item)] + week_none_day_parse_data[
                        '{}'.format(day_list_item)]
                    print(">>>>>>>>>>>>>>>>>>  daily_inc_list={}  <<<<<<<<<<<<<<<<<<<<<".format(daily_inc_list))
                    print(">>>>>>>>>>>>>>>>>>  day_list_item={}  <<<<<<<<<<<<<<<<<<<<<".format(day_list_item))
                    # all_data['w-{}'.format(week_list_item)]['d-{}'.format(day_list_item)] = daily_inc_list

templates/userprofile/admin/employee_plans.html
{% extends 'userprofile-base.html' %}
{% load static %}
{% load i18n %}
{#{% load return_objects %}#}
{% get_available_languages as languages %}
{% get_current_language as LANGUAGE_CODE %}

{% block title_container %}{% trans 'All Plans' %}{% endblock %}

{% block head_container %}
        <link href="{% static 'theme/assets/apps/css/todo.min.css' %}" rel="stylesheet" type="text/css" />

{% endblock %}


{% block content_container %}

            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <div class="page-content">
                    <!-- BEGIN PAGE BASE CONTENT -->
                    <div class="todo-main-header">
                        <h3>{{ employee.first_name }} {{ employee.last_name }}</h3>
                        <ul class="todo-breadcrumb">
                            <li>
                                <a href="{% url 'userprofile:dashboard' %}">{% trans 'Dashboard' %}</a>
                            </li>
                        </ul>
                    </div>
                    <div class="row">
                        <div class="col-lg-10 col-lg-offset-1 col-xs-12 col-sm-12">
                            <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="icon-cursor font-dark hide"></i>
                                        <span class="caption-subject font-dark bold uppercase">{% trans 'Print Plan' %}</span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <a onclick="generatePlanPdf('{% url 'userprofile:admin-pdf-plan-generate-ajax' employee.id %}','{{ csrf_token }}')" id="admin-pdf-plan-generate-button" data-ajax-url="{% url 'userprofile:admin-pdf-plan-generate-ajax' employee.id %}"
                                               class="btn btn-md btn-circle red easy-pie-chart-reload" style="width: 100%;">
                                                <i class="fa fa-print"></i> {% trans 'Click here or Ctrl + P' %}
                                            </a>
                                        </div>
                                        <div class="col-md-12" style="text-align: center;display: none;" id="admin-pdf-plan-generate-loader">
                                            <img style="height: 40px;" src="{% static 'theme/assets/custom/images/loading2.gif' %}">
                                        </div>
                                        <hr class="col-md-12"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="todo-container" id="work-plan-container" data-ajax-url="{% url 'userprofile:admin-employee-plan-ajax' employee.id  %}">
                    </div>

                    <!-- END PAGE BASE CONTENT -->
                </div>
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->


<!-- Modal -->
<div id="todo-task-modal" class="modal fade" role="dialog">
  <div class="modal-dialog" style="left: 0;">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="edit-location-order-modal-name">Map</h4>
      </div>
      <div class="modal-body" id="ajax-employee-map-div">
      </div>
    </div>

  </div>
</div>


<!-- Modal -->
<div id="action-operation-modal" class="modal fade" role="dialog">
  <div class="modal-dialog" style="left: 0;">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="change-plan-week-action-title"></h4>
      </div>
      <div class="modal-body" id="">
          <form action="" id="change-plan-week-action-form">
            {% csrf_token %}
            <div class="form-group">
                <div class="input-group">
                    <label for="single-append-text" class="control-label">{% trans 'Select Week Day' %}</label>
                    {{ action_form.second_plan }}
                </div>
            </div>
            <div class="form-group">
                <a style="display: none;" id="change-plan-week-action-button" data-ajax-url="" class="btn btn-circle green btn-outline  btn-block">
                    <i class="fa fa-edit"></i>
                    {% trans 'Submit' %}
                </a>
            </div>
          </form>
      </div>
    </div>

  </div>
</div>


<div id="edit-location-order-modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="edit-location-order-modal-name"></h4>
      </div>
      <div class="modal-body" id="edit-location-order-modal-body">
        <form>
            <div class="form-group">
                <label for="single-append-text" class="control-label">{% trans 'Select Employee' %}</label>
                <div class="input-group select2-bootstrap-append">
                    <select id="edit-location-order-modal-employee-select" class="form-control select2-allow-clear">

                    </select>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" data-select2-open="single-append-text">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <label for="single-append-text" class="control-label">{% trans 'Week' %}</label>
                <div class="input-group select2-bootstrap-append">
                    <select id="edit-location-order-modal-employee-week-select" class="form-control select2-allow-clear">
                        <option value="">{% trans 'Choose Week' %}</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" data-select2-open="single-append-text">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <label for="single-append-text" class="control-label">{% trans 'Work Day' %}</label>
                <div class="input-group select2-bootstrap-append">
                    <select id="edit-location-order-modal-employee-workday-select" class="form-control select2-allow-clear">

                    </select>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" data-select2-open="single-append-text">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </div>
            <div class="form-group">
                <label for="single-append-text" class="control-label">{% trans 'Location' %}</label>
                <div class="input-group select2-bootstrap-append">
                    <select id="edit-location-order-modal-employee-change-location-select" class="form-control select2-allow-clear">

                    </select>
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button" data-select2-open="single-append-text">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </span>
                </div>
            </div>
            <div class="form-group">
                    <a style="display: none;" onclick="changePositionLocation()" id="change-position-location-button" data-ajax-url="" class="btn btn-circle green btn-outline  btn-block" data-toggle="modal" data-target="#edit-location-order-modal">
                        <i class="fa fa-edit"></i>
                        {% trans 'Change' %}
                    </a>
            </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
      </div>
    </div>

  </div>
</div>
{% endblock %}


{% block footer_container %}
<script>

    function generateWeeklyPlanPdf($url,$id) {
        var main_print_div = $('#main-print-div');
        var admin_pdf_plan_generate_button = $('#admin-pdf-plan-weekly-generate-button-'+$id);
        var main_print_content_div = $('#main-print-content-div');
        // admin_pdf_plan_generate_button.hide();
        var succest_text_button = admin_pdf_plan_generate_button.html();
        admin_pdf_plan_generate_button.html('{% trans '<i class="fa fa-spinner" aria-hidden="true"></i> Please wait' %}');
        // admin_pdf_plan_generate_button.te();
        var $csrf = '{{ csrf_token }}';
        $.post($url, {'csrfmiddlewaretoken':$csrf})
            .done(function (data) {
                // console.log(data);
                // data_list_main_content.html(data['result'])
                // $("#action-operation-modal").modal('hide');
                // employeePlansShow();
                main_print_content_div.html(data['_html']);
                // admin_pdf_plan_generate_loader.hide();
                admin_pdf_plan_generate_button.html(succest_text_button);
                printData('main-print-div');
            });
    }
</script>
    <script src="{% static 'theme/assets/custom/employee_plans.js' %}" type="text/javascript"></script>

{% endblock %}
{% block js_block %}
        <script type="text/javascript">
            jQuery(document).bind("keyup keydown", function(e){
                if(e.ctrlKey && e.keyCode == 80){
                    generatePlanPdf('{% url 'userprofile:admin-pdf-plan-generate-ajax' employee.id %}','{{ csrf_token }}');
                    return false;
                }
            });
        </script>
        <div style="display: none;" >
            <div id="main-print-div">
                   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
                    <div id="main-print-content-div"></div>
            </div>
        </div>
    <script>
        currentMenu('main-plan');
    </script>
{% endblock %}

templates/userprofile/admin/plan_prepare.html
{% extends 'userprofile-base.html' %}
{% load static %}
{% load staticfiles %}
{% load i18n %}
{% get_available_languages as languages %}
{% get_current_language as LANGUAGE_CODE %}

{% block title_container %}{% trans 'Prepare Plans' %}{% endblock %}

{% block head_container %}

{% endblock %}


{% block content_container %}

            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <div class="page-content">
                    <!-- BEGIN PAGE HEAD-->
                    <div class="page-head">
                        <!-- BEGIN PAGE TITLE -->
                        <div class="page-title">
                            <h1>{% trans 'Prepare Plan' %}
{#                                <small></small>#}
                            </h1>
                        </div>
                    </div>
                    <!-- END PAGE HEAD-->
                    <!-- BEGIN PAGE BREADCRUMB -->
                    <ul class="page-breadcrumb breadcrumb">
                        <li>
                            <a href="{% url 'userprofile:dashboard' %}">{% trans 'Dashboard' %}</a>
                            <i class="fa fa-circle"></i>
                        </li>
                        <li>
                            <span class="active">{% trans 'Prepare Plan' %}</span>
                        </li>
                    </ul>
                    <!-- END PAGE BREADCRUMB -->
                    <!-- BEGIN PAGE BASE CONTENT -->



                    <div class="row">
                        <div class="col-lg-8 col-lg-offset-2 col-xs-12 col-sm-12">
                            <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="icon-cursor font-dark hide"></i>
                                        <span class="caption-subject font-dark bold uppercase">{% trans 'Prepare Plan' %}</span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div class="row">
                                        {% include 'userprofile/include/_plan_prepare.html' %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END PAGE BASE CONTENT -->
                </div>
                <!-- END CONTENT BODY -->
            </div>


{% endblock %}




{% block footer_container %}

{% endblock %}
{% block js_block %}
        
    <script>
        currentMenu('main-plan');
    </script>
{% endblock %}